### ISSUE TITLE
ajustar animações

### ISSUE THREAD

**Issue by ricoms** [ricoms/SEMaComp-site#4]
Escolhi um template de (http://startbootstrap.com/template-overviews/creative/) para usar como base, porém as animações de buttons e cabeçalho não está funcionando ainda.
Corrigir as animações futuramente...

**Comment by viniciusfeitosa** [comment]
O front-end é desassociado do django ou vai usar a estrutura padrão do framework. Caso a app seja uma API, devemos adotar o Djando Rest ao projeto.
